import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import vm from'node:vm';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';import matter from'gray-matter';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),after=fs.readFileSync(path.join(root,'scripts/qa-pmids.mjs'),'utf8');
// Exact condition excerpts from the reviewed Testagen candidate; fixture metadata/prose are not live research.
const realTestagenConditions={"conditions":[{"slug":"male-hormonal-health","name":"Male Hormonal Health","researchSummary":"A small adjunct branded-Testagen report describes hormone and symptom observations, with no stated random allocation, unclear arm baselines and unresolved product composition. It does not establish isolated KEDG efficacy or testosterone normalization. DOI:10.21856/j-PEP.2011.2.03.","relevantStudies":["10.21856/j-PEP.2011.2.03"],"relatedPeptides":["vilon","epithalon"]},{"slug":"male-fertility","name":"Male Fertility Support","researchSummary":"No fertility endpoint is reported in the selected human branded-product paper. A developer review asserts animal spermogram effects without an identifiable underlying original study in the reviewed passage. These sources do not establish a fertility benefit. DOI:10.21856/j-PEP.2011.2.03; DOI:10.30629/0023-2149-2020-98-3-165-177.","relevantStudies":["10.21856/j-PEP.2011.2.03","10.30629/0023-2149-2020-98-3-165-177"],"relatedPeptides":[]}]};
// Execute the real production collection prefix with only its filesystem supplied.
// Stop before resolver declarations: no fetch, fake registry success or live calls.
function collect(files,source=after){const logs=[],prefix=source.slice(0,source.indexOf('const UA =')).replace(/^import .+;\r?\n/gm,'');const sandbox={fs:{existsSync:()=>true,readdirSync:()=>Object.keys(files),readFileSync:file=>files[path.basename(file)]},path,matter,process:{argv:['node','qa-pmids.mjs','--strict']},console:{log:x=>logs.push(x),warn:x=>logs.push(x)}};vm.runInNewContext(prefix+'\nglobalThis.observed={pmids:[...pmidFiles].map(([id,files])=>({id,files:[...files]})),ncts:[...nctFiles].map(([id,files])=>({id,files:[...files]})),dois:[...doiFiles].map(([id,files])=>({id,files:[...files]})),badCites};',sandbox,{timeout:3000});return{...JSON.parse(JSON.stringify(sandbox.observed)),logs};}
const mdx=(data={},body='')=>'---\n'+JSON.stringify(data)+'\n---\n'+body;
const doiIds=result=>result.dois.map(x=>x.id).sort();
test('actual frozen final Testagen extracts the exact two DOI identities without sentence punctuation variants',()=>{const raw=mdx(realTestagenConditions),expected=['10.21856/j-PEP.2011.2.03','10.30629/0023-2149-2020-98-3-165-177'];const fixed=collect({'testagen.mdx':raw});assert.deepEqual(doiIds(fixed),expected);for(const record of fixed.dois)assert.deepEqual(record.files,['testagen.mdx']);assert.deepEqual(fixed.badCites,[]);});
test('frontmatter prose and body trim terminal period comma semicolon including mixed closers, deduplicating contexts',()=>{for(const ending of['.',',',';','),','.).;',')).',';).']){const token='10.1234/alpha',input={'first.mdx':mdx({summary:`See DOI:${token}${ending}`},`Paper https://doi.org/${token}${ending}`),'second.mdx':mdx({},`DOI:${token}${ending}`)};const result=collect(input);assert.deepEqual(result.dois,[{id:token,files:['first.mdx','second.mdx']}],ending);}});
test('valid balanced and nested DOI parentheses survive in standalone fields, DOI prose, URL and Markdown contexts',()=>{for(const id of['10.1016/S2213-8587(26)00125-7','10.1234/alpha(beta)','10.1234/alpha(beta(gamma))']){const result=collect({'a.mdx':mdx({doi:id,source:'DOI:'+id,summary:`Recorded DOI:${id}.`},`[Paper](https://doi.org/${id}). (DOI:${id});`)});assert.deepEqual(doiIds(result),[id]);}});
test('internal DOI punctuation and exact standalone suffix punctuation remain unchanged',()=>{const ids=['10.1234/alpha.beta,gamma;delta','10.1234/ends.','10.1234/ends,','10.1234/ends;','10.1234/alpha(beta)'];for(const id of ids){const result=collect({'a.mdx':mdx({doi:id,relevantStudies:[id],citations:['DOI:'+id]})});assert.deepEqual(doiIds(result),[id],id);}assert.deepEqual(doiIds(collect({'a.mdx':mdx({},'DOI:10.1234/a.b,c;d.')})),['10.1234/a.b,c;d']);});
test('exact standalone DOI URLs in citation fields preserve suffix punctuation; embedded prose URLs trim only delimiters',()=>{for(const suffix of['ends.','ends,','ends;','alpha(beta)','alpha%28beta%29']){const id='10.1234/'+suffix;for(const origin of['https://doi.org/','http://dx.doi.org/'])assert.deepEqual(doiIds(collect({'a.mdx':mdx({source:origin+id,citations:[origin+id]})})),[id]);}assert.deepEqual(doiIds(collect({'a.mdx':mdx({summary:'See https://doi.org/10.1234/ends.'},'[Paper](https://doi.org/10.1234/ends).')})),['10.1234/ends']);assert.deepEqual(doiIds(collect({'a.mdx':mdx({source:'https://doi.org/10.1234/ends.'},'See https://doi.org/10.1234/ends.')})),['10.1234/ends','10.1234/ends.']);});
test('uppercase context prefixes preserve the exact identifier case and deduplicate only exact IDs',()=>{const result=collect({'a.mdx':mdx({summary:'dOi:10.1234/MiXeD.'},'https://DOI.ORG/10.1234/MiXeD, DOI:10.1234/mixed.')});assert.deepEqual(doiIds(result),['10.1234/MiXeD','10.1234/mixed']);});
test('standalone DOI-like prose is normalized once, avoiding a second conflicting exact form',()=>{assert.deepEqual(doiIds(collect({'a.mdx':mdx({summary:'DOI:10.1234/alpha.'})})),['10.1234/alpha']);assert.deepEqual(doiIds(collect({'a.mdx':mdx({summary:'10.1234/alpha.'})})),['10.1234/alpha']);});
test('malformed and empty tokens produce no empty DOI; placeholder worklist and PMID/NCT extraction are unchanged',()=>{const files={'a.mdx':mdx({pmid:'N/A',doi:'DOI:10.1234/',relevantStudies:['TBD','12345678','NCT01234567']},'DOI: DOI:10.123/abc DOI:10.1234567890/abc DOI:10.1234/ DOI:10.1234/... DOI:10.1234/). PMID:87654321 NCT07654321')};const fixed=collect(files);assert.deepEqual(doiIds(fixed),[]);assert.deepEqual(fixed.pmids.map(x=>x.id),['12345678','87654321']);assert.deepEqual(fixed.ncts.map(x=>x.id),['NCT01234567','NCT07654321']);assert.ok(fixed.badCites.some(x=>x.value==='TBD'));});
test('unbalanced opening parentheses are not guessed or silently completed; only trailing excess closers are removed',()=>{assert.deepEqual(doiIds(collect({'a.mdx':mdx({},'DOI:10.1234/alpha(beta. DOI:10.1234/alpha(beta)).')})),['10.1234/alpha(beta','10.1234/alpha(beta)']);});
test('quoted HTML href and Markdown bracket contexts retain citation-file ownership',()=>{const result=collect({'one.mdx':mdx({},'<a href="https://doi.org/10.1234/abc">Paper</a> [DOI:10.1234/abc]'),'two.mdx':mdx({summary:'DOI:10.1234/abc.'})});assert.deepEqual(result.dois,[{id:'10.1234/abc',files:['one.mdx','two.mdx']}]);});
test('balanced internal angle pairs and SICI punctuation survive DOI/URL prose and exact fields; only extra autolink closers trim',()=>{for(const id of['10.1234/alpha<beta>gamma','10.1002/(SICI)1097-0258(19980815)17:15<1763::AID-SIM974>3.0.CO;2-F','10.1234/alpha<beta>','10.1234/a%3Cb%3E']){for(const context of[`DOI:${id}.`,`See https://doi.org/${id};`,`<https://doi.org/${id}>.`,`[Paper](https://doi.org/${id}).`,`(<https://doi.org/${id}>).;`])assert.deepEqual(doiIds(collect({'a.mdx':mdx({summary:context},context)})),[id],context);assert.deepEqual(doiIds(collect({'a.mdx':mdx({doi:id,source:'https://doi.org/'+id,citations:[id]})})),[id]);}assert.deepEqual(doiIds(collect({'a.mdx':mdx({},'<https://doi.org/10.1234/abc>')})),['10.1234/abc']);});
